### PR TITLE
Run ruff lints

### PR DESCRIPTION
**Pull request by meator**
This PR fixes some lint errors.

`crazy-complete` unfortunately doesn't include any configration files for Python formatters nor does it include a style guide, so I have used my own best judgement. My linter/formatter of choice is [ruff](https://docs.astral.sh/ruff/).

Most of these commits are stylistic, but some are not. I consider commits dc993027ac3828cf760b68d60690a884e3aae6d7, 1497c4c8345650b2a5e22374b1bc4a94bdde5052, f0661378aac1a980f69ce8605438b90a483018bd and feed6ab6f95864129eea5a01426f7e3af77a9e3d important.

The first commits fix docstrings. Your docstring style is very inconsistent braph. Ruff really doesn't like that. You often exceed the maximum acceptable length of a docstring summary line. Many public functions/classes lack a docstring.

These commits are a combination of ruff's automatic fixer and of my own efforts to fix the warnings. I have reviewed all automatic fixes applied by ruff.

### CODE REVIEW

**Comment by braph** [comment]
Hello Meator,

your fixes look good to me so far, with some exceptions:

- [c8cb21f](https://github.com/crazy-complete/crazy-complete/pull/22/commits/c8cb21fbd01b271fc01131d0c2056eb803cbb3a6):

  This actually "breaks" the script, because it doesn't import the development version of crazy-complete, but rather the installed version.

- [feed6ab](https://github.com/crazy-complete/crazy-complete/pull/22/commits/feed6ab6f95864129eea5a01426f7e3af77a9e3d):

  I don't like using `except Exception`. Your commit message states that it is "dangerous" to catch exceptions that aren't derived from `Exception`, but actually it isn't possible to raise objects that aren't derived from `Exception` anyway. Explicitly catching the `Exception` type just clutters the code IMHO.

- [e1262de](https://github.com/crazy-complete/crazy-complete/pull/22/commits/e1262de01f3546759c20f9fdec9031fcaf5921e3):

  The same applies for this commit. `raise Exception(...) from None` just clutters the code. There really isn't any benefit from being that verbose.

If you revert those commits I'm willing to merge the PR.

Also, can you please tell me which options you passed to `ruff`? I ran `ruff check` and it didn't give me as many warnings as it should have.

**Comment by meator** [comment]
> * [c8cb21f](https://github.com/crazy-complete/crazy-complete/pull/22/commits/c8cb21fbd01b271fc01131d0c2056eb803cbb3a6):
>   This actually "breaks" the script, because it doesn't import the development version of crazy-complete, but rather the installed version.

Ah, I didn't notice that. Custom import logic can be difficult to get right, it is usually best to leave this stuff to Python.

> * [feed6ab](https://github.com/crazy-complete/crazy-complete/pull/22/commits/feed6ab6f95864129eea5a01426f7e3af77a9e3d):
>   I don't like using `except Exception`. Your commit message states that it is "dangerous" to catch exceptions that aren't derived from `Exception`, but actually it isn't possible to raise objects that aren't derived from `Exception` anyway. Explicitly catching the `Exception` type just clutters the code IMHO.

It is impossible to raise objects that are not derived from **Base**Exception. `Exception` is a subclass of `BaseException`. The most notable counterexample is `KeyboardInterrupt`. `KeyboardInterrupt` is a subclass of `BaseException`, but not of `Exception`. The consequence of using plain `except:` is that if `crazy-complete` halts/reaches a cycle, attempts to interrupt it will be catched too, which can have unintended consequences. It is best to leave `KeyboardInterrupt` and other exceptions which are not based off of `Exception` untouched unless you are really sure that you want to handle these.

This behavior is dangerous, because it can lead to important system exceptions and `KeyboardInterrupt` being handled inappropriately.

> * [e1262de](https://github.com/crazy-complete/crazy-complete/pull/22/commits/e1262de01f3546759c20f9fdec9031fcaf5921e3):
>   The same applies for this commit. `raise Exception(...) from None` just clutters the code. There really isn't any benefit from being that verbose.

This change is far from stylistic. It facilitates exception chaining. Here's example code:

```py
from typing import Any
import traceback

def get_name1(input: dict[str, Any]) -> str:
    try:
        return input["name"]
    except KeyError:
        raise ValueError("Expected `name` in input!")

def get_name2(input: dict[str, Any]) -> str:
    try:
        return input["name"]
    except KeyError as exc:
        raise ValueError("Expected `name` in input!") from exc

def get_name3(input: dict[str, Any]) -> str:
    try:
        return input["name"]
    except KeyError:
        raise ValueError("Expected `name` in input!") from None

try:
    get_name1({"namme": "oops, a typo"})
except Exception:
    traceback.print_exc()
print("-" * 100)
try:
    get_name2({"namme": "oops, a typo"})
except Exception:
    traceback.print_exc()
print("-" * 100)
try:
    get_name3({"namme": "oops, a typo"})
except Exception:
    traceback.print_exc()
```

Output:

```pytb
Traceback (most recent call last):
  File "/tmp/a.py", line 6, in get_name1
    return input["name"]
           ~~~~~^^^^^^^^
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/a.py", line 23, in <module>
    get_name1({"namme": "oops, a typo"})
  File "/tmp/a.py", line 8, in get_name1
    raise ValueError("Expected `name` in input!")
ValueError: Expected `name` in input!
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/a.py", line 12, in get_name2
    return input["name"]
           ~~~~~^^^^^^^^
KeyError: 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/a.py", line 28, in <module>
    get_name2({"namme": "oops, a typo"})
  File "/tmp/a.py", line 14, in get_name2
    raise ValueError("Expected `name` in input!") from exc
ValueError: Expected `name` in input!
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/a.py", line 33, in <module>
    get_name3({"namme": "oops, a typo"})
  File "/tmp/a.py", line 20, in get_name3
    raise ValueError("Expected `name` in input!") from None
ValueError: Expected `name` in input!
```

The first `raise` (`raise ValueError()`) expresses that Python was handling the `KeyError`, but another unexpected error has occurred while handling it (the error being `ValueError`). This means that there are two unexpected states.

The second `raise` (`raise ValueError() from exc`) expresses that `ValueError` is the main exception and that it has been caused by `KeyError`. There is only a single unexpected state, the `except` handler does not have any unexpected state in it.

The third `raise` (`raise ValueError() from None`) expresses that there is a `ValueError`. The `KeyError` is considered an implementation detail that should not be exposed to the user. The `KeyError` is fully handled internally, so there should be no mention of it in the resulting exception.

I prefer to use the latter two states. It is best to avoid the first one in an `except` block (and in context guards and other places which deal with exceptions).

**Comment by meator** [comment]
Here's my `pyproject.toml` file (I have added comments):

```toml
[tool.ruff.lint]
# First four warning types are enabled by default.
select = ["E4", "E7", "E9", "F", "C90", "I", "N", "D", "B"]
ignore = [
  # crazy-complete uses single quotes for everything
  "D300", # triple-single-quotes
  # These turn off warnings about undocumented public interface. There are too
  # many of these for them to be useful
  "D100", # undocumented-public-module
  "D101", # undocumented-public-class
  "D102", # undocumented-public-method
  "D103", # undocumented-public-function
  "D105", # undocumented-magic-method
  "D107", # undocumented-public-init
  # Unsorted imports are also annoying to deal with.
  "I001", # unsorted-imports
  # This gets triggered because the summary line of docstrings is too long.
  # It would require rewriting a lot of documentation to fix this in the entire
  # codebase
  "D205", # blank-line-after-summary
  "D212", # multi-line-summary-first-line
]
# These don't seem to be especially important.
exclude = ["completions/fpm/old/**", "crazy_complete/.trash.py"]
pydocstyle.convention = "google"

[tool.ruff.lint.per-file-ignores]
# I wasn't sure about this warning, so I didn't want to touch it.
"crazy_complete/argparse_mod.py" = ["B010"] # set-attr-with-constant
"crazy_complete/bash.py" = ["N806"] # non-lowercase-variable-in-function

[tool.ruff.format]
quote-style = "single"
```

I have taken the lint categories from https://github.com/enkore/j4-dmenu-desktop/blob/develop/tests/system_tests/pyproject.toml. I don't remember how I chose the additional lint categories, but I usually try to enable as many warnings as possible in the code I write.

**Comment by braph** [comment]
Hey Meator,

I'm sorry; I didn't know about the details of Python's exception hierarchy, nor did I know about the difference between `raise Exception` and `raise Exception from None`.

Now that you've explained them to me, your commits indeed makes sense.

I will include the `pyproject.toml` file into the project.

Thanks for being so patient with me!

**Pull request merged**
